---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-server-2012r2

suites:
  - name: default
    includes:
      - windows-server-2012r2
    run_list:
      - recipe[cis-benchmarks::default]
    attributes:
      cis-benchmarks:
        benchmark: windows_server_2012r2
        windows_server_2012r2:
          security_policy:
            privilege_rights:
              SeDenyNetworkLogonRight: Guests
              SeDenyRemoteInteractiveLogonRight: Guests
