---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-server-2012r2

suites:
  - name: level-1-member-server
    includes:
      - windows-server-2012r2
    run_list:
      - recipe[cis-benchmarks::default]
    attributes:
      cis-benchmarks:
        windows_server_2012r2:
          security_policy:
            privilege_rights:
              SeDenyNetworkLogonRight: Guests
              SeDenyRemoteInteractiveLogonRight: Guests
            system_access:
              EnableAdminAccount: 1
              NewAdministratorName: Administrator
          registry_keys:
            '9.3.5':
              name: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile
              values:
                name: AllowLocalPolicyMerge
                type: dword
                data: 1
            '9.3.6':
              name: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile
              values:
                name: AllowLocalIPsecPolicyMerge
                type: dword
                data: 1
            '18.6.1':
              name: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system
              values:
                name: LocalAccountTokenFilterPolicy
                type: dword
                data: 1
            '18.9.86.2.3':
              name: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service
              values:
                name: AllowUnencryptedTraffic
                type: dword
                data: 1

  - name: level-2-member-server
    includes:
      - windows-server-2012r2
    run_list:
      - recipe[cis-benchmarks::default]
    attributes:
      cis-benchmarks:
        windows_server_2012r2:
          profile_level: 2
          security_policy:
            privilege_rights:
              SeDenyNetworkLogonRight: Guests
              SeDenyRemoteInteractiveLogonRight: Guests
            system_access:
              EnableAdminAccount: 1
              NewAdministratorName: Administrator
          registry_keys:
            '2.3.10.4':
              name: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa
              values:
                name: disabledomaincreds
                type: dword
                data: 0
            '9.3.5':
              name: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile
              values:
                name: AllowLocalPolicyMerge
                type: dword
                data: 1
            '9.3.6':
              name: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile
              values:
                name: AllowLocalIPsecPolicyMerge
                type: dword
                data: 1
            '18.6.1':
              name: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system
              values:
                name: LocalAccountTokenFilterPolicy
                type: dword
                data: 1
            '18.9.86.2.2':
              name: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service
              values:
                name: AllowAutoConfig
                type: dword
                data: 1
            '18.9.86.2.3':
              name: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service
              values:
                name: AllowUnencryptedTraffic
                type: dword
                data: 1
            '18.9.87.1':
              name: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service\WinRS
              values:
                name: AllowRemoteShellAccess
                type: dword
                data: 1
