---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windowsserver-2012r2

suites:
  - name: level-1-member-server
    includes:
      - windowsserver-2012r2
    run_list:
      - recipe[cis-benchmarks::default]
    attributes:
      cis-benchmarks:
        windows_server_2012r2:
          security_policy:
            privilege_rights:
              SeDenyNetworkLogonRight: Guests
              SeDenyRemoteInteractiveLogonRight: Guests
            system_access:
              EnableAdminAccount: 1
              NewAdministratorName: Administrator
          registry_keys:
            '9.3.5': ''
            '9.3.6': ''
            '18.6.1': ''
            '18.9.86.2.3': ''

  - name: level-2-member-server
    includes:
      - windowsserver-2012r2
    run_list:
      - recipe[cis-benchmarks::default]
    attributes:
      cis-benchmarks:
        windows_server_2012r2:
          profile_level: 2
          security_policy:
            privilege_rights:
              SeDenyNetworkLogonRight: Guests
              SeDenyRemoteInteractiveLogonRight: Guests
            system_access:
              EnableAdminAccount: 1
              NewAdministratorName: Administrator
          registry_keys:
            '2.3.10.4': ''
            '9.3.5': ''
            '9.3.6': ''
            '18.6.1': ''
            '18.9.86.2.2': ''
            '18.9.86.2.3': ''
            '18.9.87.1': ''

  - name: level-1-domain-controller
    provisioner:
      name: chef_zero
      retry_on_exit_code:
        - 1
        - 35
      max_retries: 3
      wait_for_retry: 30
      client_rb:
        exit_status: :enabled
        client_fork: false
    includes:
      - windowsserver-2012r2
    run_list:
      - recipe[cis-benchmarks-test::benchmark_windows_server_2012r2_domain_controller]
    attributes:
      cis-benchmarks:
        windows_server_2012r2:
          profile_name: domain_controller
          security_policy:
            privilege_rights:
            system_access:
              EnableAdminAccount: 1
              NewAdministratorName: Administrator
          registry_keys:
            '18.9.86.2.3': ''

  - name: level-2-domain-controller
    provisioner:
      name: chef_zero
      retry_on_exit_code:
        - [35, 1]
      max_retries: 5
      wait_for_retry: 60
      client_rb:
        exit_status: :enabled
    includes:
      - windowsserver-2012r2
    run_list:
      - recipe[cis-benchmarks-test::benchmark_windows_server_2012r2_domain_controller]
    attributes:
      cis-benchmarks:
        windows_server_2012r2:
          profile_name: domain_controller
          profile_level: 2
          security_policy:
            privilege_rights:
            system_access:
              EnableAdminAccount: 1
              NewAdministratorName: Administrator
          registry_keys:
            '2.3.10.4': ''
            '18.9.86.2.2': ''
            '18.9.86.2.3': ''
            '18.9.87.1': ''
