---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-server-2012r2

suites:
  - name: level-1-member-server
    includes:
      - windows-server-2012r2
    run_list:
      - recipe[cis-benchmarks::default]
    attributes:
      cis-benchmarks:
        windows_server_2012r2:
          security_policy:
            privilege_rights:
              SeDenyNetworkLogonRight: Guests
              SeDenyRemoteInteractiveLogonRight: Guests
          registry_keys:
            '18.6.1': ~

  - name: level-2-member-server
    includes:
      - windows-server-2012r2
    run_list:
      - recipe[cis-benchmarks::default]
    attributes:
      cis-benchmarks:
        windows_server_2012r2:
          profile_level: 2
          security_policy:
            privilege_rights:
              SeDenyNetworkLogonRight: Guests
              SeDenyRemoteInteractiveLogonRight: Guests
          registry_keys:
            '2.3.10.4': ~
            '18.6.1': ~
            '18.9.86.2.2': ~
            '18.9.87.1': ~
